name: Build Executable

on:
  schedule:
    - cron: '0 3 * * 0'
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: powershell
      run: |
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
        .\installResources.ps1

    - name: Build executable
      shell: powershell
      run: pyinstaller --onefile converter.py

    - name: Verify build output
      shell: powershell
      run: dir dist

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: converter-exe
        path: dist/converter.exe
